# docker-compose.yml
# Этот файл определяет, как Docker Compose должен собирать и запускать ваше приложение.

# Указывает версию синтаксиса Docker Compose. '3.8' - это распространенная и актуальная версия.
version: '3.8'

# Секция 'services' определяет различные сервисы (контейнеры), которые составляют ваше приложение.
services:
  # Определяем наш фронтенд-сервис. Вы можете дать ему любое имя, например 'web' или 'app'.
  frontend:
    # Инструкции для сборки Docker-образа для этого сервиса.
    build:
      # 'context: .' указывает Docker Compose, что Dockerfile находится в текущей директории
      # (т.е. в корне вашего проекта).
      context: .
      # 'dockerfile: Dockerfile' указывает имя Dockerfile для сборки образа.
      dockerfile: Dockerfile
    
    # Задаем имя для создаваемого контейнера. Это упрощает его идентификацию.
    container_name: my-portfolio-frontend

    # Определяем сопоставление портов между хост-машиной и контейнером.
    # Формат: "HOST_PORT:CONTAINER_PORT"
    # Здесь мы пробрасываем порт 80 контейнера (где Nginx слушает) на порт 80 вашей хост-машины.
    # Это значит, что вы сможете получить доступ к приложению через http://localhost:80 или просто http://localhost.
    ports:
      - "80:80" 
    
    # Инструкция для Docker, чтобы он автоматически перезапускал контейнер,
    # если он по какой-либо причине остановится (например, при сбое или перезагрузке сервера).
    restart: always 
